# Config file dedicated to the user's personal zshrc profile shared between all exegol containers.
# This file is sourced in /root/.zshrc file.
# Alternatively, the /opt/my-resources/setup/load_user_setup.sh file can be used to operate the change once (instead of sourcing a file for each zsh instance)

#start tmux at startup
if [ "$TMUX" = "" ]; then tmux; fi

# Color correction for zsh-syntax-highlighting                                                                                     │
 ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#FFFFFF' 

# history size
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000

#personnal alias for fzf in personnal wordlists
alias fzf-wordlists-my='find /opt/my-resources/NecessaryPayloads -type f | fzf'
